### ISSUE TITLE
项目启动后 修改相应本地地址后无法出现登录界面

### ISSUE THREAD

**Issue by cooper-q** [canyuegongzi/simple-user-center-web#3]
- 如果访问 http://127.0.0.1:8082/user-login-cas-web 就会一直不停的重复请求和刷新

**Comment by cooper-q** [comment]
- 并且如果访问 http://127.0.0.1:8082/user-login-cas-web 无法出现登录界面

**Comment by canyuegongzi** [comment]
env中有配置相关跳转地址的选项，需要单点登录的话，需要单独启动user-login-cas-web前端工程

**Comment by cooper-q** [comment]
> env中有配置相关跳转地址的选项，需要单点登录的话，需要单独启动user-login-cas-web前端工程

感谢回复

**Comment by cooper-q** [comment]
> env中有配置相关跳转地址的选项，需要单点登录的话，需要单独启动user-login-cas-web前端工程

在线的现在返回 dddddd 进不去啦
